"""Encoded clause objects from Colorado HB24-1058 and California SB 1223.

Summaries cite public statute text. This is not legal advice. Checkability
is a research judgment about whether policy text alone can support a
machine observation, not a claim about legal sufficiency.
"""

from __future__ import annotations

from neuroprivacy.schemas import StatutoryClause

# Colorado HB24-1058 (2024) amends the Colorado Privacy Act, C.R.S. § 6-1-1301
# et seq. California SB 1223 (2024) amends Civ. Code § 1798.140 (CCPA/CPRA).
CLAUSES: tuple[StatutoryClause, ...] = (
    StatutoryClause(
        clause_id="CO-DEF-NEURAL",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1303 (as amended by HB24-1058)",
        summary=(
            "Neural data is information generated by measuring activity of an "
            "individual's central or peripheral nervous system, and is included "
            "in biological data."
        ),
        checkability="policy_text",
        schema_fields=["names_neural_data", "covers_generic_device_data"],
        notes=(
            "A policy can name the category. Whether collected data meets "
            "the definition is product-level."
        ),
    ),
    StatutoryClause(
        clause_id="CO-SENSITIVE",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1303 (sensitive data definition)",
        summary="Neural data is classified as sensitive data under the Colorado Privacy Act.",
        checkability="policy_text",
        schema_fields=["names_neural_data"],
        notes="Observable if the policy lists neural data as sensitive personal information.",
    ),
    StatutoryClause(
        clause_id="CO-CONSENT",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1308(7)",
        summary="A controller shall not process sensitive data without consent.",
        checkability="policy_text",
        schema_fields=["states_consent_for_sensitive"],
        notes="Policy may claim consent. Actual consent UX is network_or_product.",
    ),
    StatutoryClause(
        clause_id="CO-DELETE",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1306(1)(d)",
        summary="A consumer may request deletion of personal data.",
        checkability="policy_text",
        schema_fields=["grants_deletion", "retention_conflicts_deletion"],
    ),
    StatutoryClause(
        clause_id="CO-ACCESS",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1306(1)(b)",
        summary="A consumer may confirm processing of personal data and access it.",
        checkability="policy_text",
        schema_fields=[],
        notes="Phase 0 schema does not encode an access-right field. Unmeasured as a field.",
    ),
    StatutoryClause(
        clause_id="CO-CORRECT",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1306(1)(c)",
        summary="A consumer may request correction of inaccurate personal data.",
        checkability="policy_text",
        schema_fields=[],
        notes="Phase 0 schema does not encode a correction-right field.",
    ),
    StatutoryClause(
        clause_id="CO-OPTOUT",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1306(1)(a)",
        summary="A consumer may opt out of sale, targeted advertising, or profiling.",
        checkability="policy_text",
        schema_fields=["discloses_sale"],
    ),
    StatutoryClause(
        clause_id="CO-PURPOSE",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1308(1)–(3)",
        summary="Duty of purpose specification, data minimization, and duty of care.",
        checkability="policy_text",
        schema_fields=["states_purpose_limitation"],
        notes="Stated purpose language is checkable; operational minimization is not.",
    ),
    StatutoryClause(
        clause_id="CO-DPA",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1309",
        summary="Data protection assessment required for processing sensitive data.",
        checkability="internal_record",
        notes="Assessments are internal. Policy text cannot prove one exists.",
    ),
    StatutoryClause(
        clause_id="CO-PROCESSOR",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1305",
        summary="Processor duties and contract requirements for processing personal data.",
        checkability="internal_record",
        notes="Vendor-processor contracts are not public policy text.",
    ),
    StatutoryClause(
        clause_id="CO-THRESHOLD",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1304",
        summary="CPA applicability thresholds (consumers, revenue, or revenue-from-sale).",
        checkability="cannot_check",
        notes="Applicability is a facts-and-figures question, not a policy clause.",
    ),
    StatutoryClause(
        clause_id="CO-TRANSMIT",
        statute="CO_HB24_1058",
        citation="C.R.S. § 6-1-1308 (processing duties) applied to device telemetry",
        summary="Whether neural signals leave the device contrary to stated purpose.",
        checkability="network_or_product",
        notes="Requires operator-owned device observation. Gated; off in Phase 0.",
    ),
    StatutoryClause(
        clause_id="CA-DEF-NEURAL",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.140 (SB 1223 amendment)",
        summary=(
            "Neural data means information generated by measuring activity of a "
            "consumer's central or peripheral nervous system that is not inferred "
            "from non-neural information."
        ),
        checkability="policy_text",
        schema_fields=["names_neural_data"],
    ),
    StatutoryClause(
        clause_id="CA-SPI",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.140 (sensitive personal information)",
        summary="Neural data is added to the sensitive personal information list.",
        checkability="policy_text",
        schema_fields=["names_neural_data"],
    ),
    StatutoryClause(
        clause_id="CA-NOTICE",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.100",
        summary="Notice at collection must identify SPI categories collected.",
        checkability="policy_text",
        schema_fields=["names_neural_data", "covers_generic_device_data"],
    ),
    StatutoryClause(
        clause_id="CA-POLICY-LIST",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.130",
        summary="Privacy policy must list SPI categories collected.",
        checkability="policy_text",
        schema_fields=["names_neural_data"],
    ),
    StatutoryClause(
        clause_id="CA-LIMIT",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.121",
        summary="Consumer right to limit use and disclosure of sensitive personal information.",
        checkability="policy_text",
        schema_fields=["states_purpose_limitation", "discloses_sharing"],
    ),
    StatutoryClause(
        clause_id="CA-SALE",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.120",
        summary="Right to opt out of sale or sharing of personal information.",
        checkability="policy_text",
        schema_fields=["discloses_sale", "discloses_sharing"],
    ),
    StatutoryClause(
        clause_id="CA-INFERENCE",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.140 neural-data definition (non-inference clause)",
        summary="Neural data does not include information inferred from non-neural information.",
        checkability="cannot_check",
        notes="Whether a vendor infers 'focus' from clickstream is not in the privacy policy.",
    ),
    StatutoryClause(
        clause_id="CA-CONTRACT",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.140 (service provider / contractor)",
        summary="Service-provider contracts must restrict SPI use.",
        checkability="internal_record",
    ),
    StatutoryClause(
        clause_id="CA-ENFORCE",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.199.40 et seq. (CPPA / AG enforcement)",
        summary="Enforcement is by the Agency and the Attorney General.",
        checkability="cannot_check",
        notes="Enforcement posture is not a vendor-policy fact.",
    ),
    StatutoryClause(
        clause_id="CA-DEVICE",
        statute="CA_SB_1223",
        citation="Cal. Civ. Code § 1798.121 applied to on-device neural streams",
        summary="Whether SPI use is limited in the running product, not only in the policy.",
        checkability="network_or_product",
        notes="Optional, operator-owned devices only. Off in Phase 0.",
    ),
)


def all_clauses() -> tuple[StatutoryClause, ...]:
    return CLAUSES


def clauses_by_statute(statute: str) -> list[StatutoryClause]:
    return [clause for clause in CLAUSES if clause.statute == statute]


def coverage_counts() -> dict[str, int]:
    total = len(CLAUSES)
    policy = sum(1 for clause in CLAUSES if clause.machine_checkable_from_policy)
    return {
        "n_clauses": total,
        "n_policy_text": policy,
        "n_network_or_product": sum(1 for c in CLAUSES if c.checkability == "network_or_product"),
        "n_internal_record": sum(1 for c in CLAUSES if c.checkability == "internal_record"),
        "n_cannot_check": sum(1 for c in CLAUSES if c.checkability == "cannot_check"),
    }
