"""Fill the memo, evaluation page, data page, and README measured blocks."""

from __future__ import annotations

from pathlib import Path

from _lib import read_json

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
EA = HERE / "extraction_accuracy" / "results"
SC = HERE / "statute_coverage" / "results"
PD = HERE / "policy_drift" / "results"


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def _table_from_md(path: Path) -> str:
    lines = [line for line in _md(path).splitlines() if line.startswith("|")]
    return "\n".join(lines)


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    ea = read_json(EA / "results.json")
    sc = read_json(SC / "results.json")
    pd = read_json(PD / "results.json")
    ea_table = _table_from_md(EA / "results.md")
    cost_lines = [
        f"- Documents extracted in extraction_accuracy: {ea['n_documents']}",
        f"- Mean field F1: {ea['mean_field_f1']:.3f}",
        f"- Status accuracy: {ea['status_accuracy']:.3f}",
        "- Live LLM USD / document: unmeasured",
        "- API RTT: unmeasured",
        f"- Drift snapshots scored: {pd['n_snapshots']}",
        f"- Observed month-to-month change rate: {pd['change_rate']:.3f}",
    ]
    filled = (
        template.replace("{{EA_N}}", str(ea["n_documents"]))
        .replace("{{EA_TABLE}}", ea_table)
        .replace("{{EA_DECISION}}", str(ea["decision"]))
        .replace("{{EA_F1}}", f"{ea['mean_field_f1']:.3f}")
        .replace("{{EA_SUMMARY}}", _md(EA / "results.md").split("##")[0].strip())
        .replace("{{EA_KW_MISS}}", str(ea["keyword_misses_generic"]))
        .replace("{{EA_GENERIC}}", str(ea["n_generic_gold"]))
        .replace("{{SC_N}}", str(sc["n_clauses"]))
        .replace(
            "{{SC_SUMMARY}}",
            f"Policy-text fraction = {sc['n_policy_text']}/{sc['n_clauses']} "
            f"= {sc['policy_text_fraction']:.3f}.",
        )
        .replace("{{SC_DECISION}}", str(sc["decision"]))
        .replace("{{PD_SNAPSHOTS}}", str(pd["n_snapshots"]))
        .replace(
            "{{PD_SUMMARY}}",
            f"Change rate = {pd['n_changes']}/{pd['n_transitions']} "
            f"= {pd['change_rate']:.3f}. Cadence = {pd['recommended_cadence']}.",
        )
        .replace("{{PD_DECISION}}", str(pd["decision"]))
        .replace("{{COST_MODEL}}", "\n".join(cost_lines))
    )
    return filled


def render_eval() -> str:
    ea = _md(EA / "results.md")
    sc = _md(SC / "results.md")
    pd = _md(PD / "results.md")
    ea_json = read_json(EA / "results.json")
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. "
        "Live public-policy hold-out numbers do not exist yet. "
        "The mean field F1 below is the baseline a live extractor must beat.\n\n"
        f"Baseline (rules+cache extractor) mean field F1: **{ea_json['mean_field_f1']:.3f}** "
        f"(n={ea_json['n_documents']}).\n\n"
        f"{ea}\n\n{sc}\n\n{pd}\n"
    )


def render_data() -> str:
    ea = read_json(EA / "results.json")
    sc = read_json(SC / "results.json")
    pd = read_json(PD / "results.json")
    return (
        "# Data\n\n"
        "Phase 0 does not fetch live vendor policies or capture device traffic. "
        "The committed objects are:\n\n"
        "- `data/sample/*.html` — four designed demo policies "
        "(vendor-a/b/c and two vendor-d snapshots; see `data/sample/README.md`)\n"
        "- `data/sample/llm_cache.json` — prompt-hash-keyed extractor cache; no API key\n"
        f"- `research/phase0/extraction_accuracy/probe_set/documents.json` — "
        f"{ea['n_documents']} labeled synthetic snippets\n"
        f"- `research/phase0/policy_drift/probe_set/snapshots.json` — "
        f"{pd['n_snapshots']} synthetic monthly snapshots\n"
        f"- `src/neuroprivacy/statutes.py` — {sc['n_clauses']} encoded CO/CA clauses\n\n"
        "No consumer-identifiable data. No authenticated scrape. License notes "
        "for the production sources (HB24-1058, SB 1223, public vendor pages) "
        "are in `docs/phase-0/research-memo.md` §3.\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    readme_path = ROOT / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    ea = read_json(EA / "results.json")
    sc = read_json(SC / "results.json")
    pd = read_json(PD / "results.json")
    body = (
        "| System | Metric | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Rules+cache extractor (Phase 0) | mean field F1 {ea['mean_field_f1']:.3f} | "
        f"{ea['n_documents']} | vs hand labels; "
        f"κ vs keyword {ea['kappa_extractor_vs_keyword']:.3f} |\n"
        f"| Keyword baseline | κ vs extractor {ea['kappa_extractor_vs_keyword']:.3f} | "
        f"{ea['n_documents']} | Misses generic device-data cover "
        f"({ea['keyword_misses_generic']}/{ea['n_generic_gold']}) |\n"
        f"| Statute coverage | policy-text {sc['policy_text_fraction']:.3f} | "
        f"{sc['n_clauses']} | CO HB24-1058 + CA SB 1223 encoded clauses |\n"
        f"| Policy drift | change rate {pd['change_rate']:.3f} | "
        f"{pd['n_snapshots']} | cadence {pd['recommended_cadence']} |\n"
        "| Live public-policy hold-out | Phase 3 | — | Must beat Phase 0 mean F1 |\n"
    )
    text = _replace_block(text, "<!-- EVAL_TABLE_BEGIN -->", "<!-- EVAL_TABLE_END -->", body)
    readme_path.write_text(text, encoding="utf-8")


def main() -> None:
    memo = render_memo()
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(memo, encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    (ROOT / "docs" / "DATA.md").write_text(render_data(), encoding="utf-8")
    if (ROOT / "README.md").exists():
        patch_readme()
    print("wrote memo, EVALUATION.md, DATA.md, and README results")


if __name__ == "__main__":
    main()
